### ISSUE TITLE
Possible crash? [question]

### ISSUE THREAD

**Issue by bgveenstra** [sfnewzgirl/internauts-project-vagabond#27]
What does this line do if there is no current user and the session has no user id:

https://github.com/sfnewzgirl/internauts-project-vagabond/blob/master/app/helpers/sessions_helper.rb#L7

**Comment by sfnewzgirl** [comment]
We've tested this again and it does not crash. If a user tries to post a comment without being logged in (current_user) they will be redirected to the log in page when they submit the post. This action is in the posts controller. 

```
def create
    city_id = params[:city_id]
    @city = City.find_by(id: city_id)
    if current_user
      @post = Post.create(post_params)
      if @post.save
        redirect_to city_path
      else
        render 'new'
      end
    else
     flash[:create_post_error] = "Please log in."
     redirect_to login_path
    end
```
